"""initial schema

Revision ID: 562da9d71450
Revises: 
Create Date: 2026-08-20 16:42:07.146163

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '562da9d71450'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('framework',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('repo_url', sa.String(length=300), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('knowledge_asset',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('direction', sa.Enum('model', 'chain', 'feature', name='direction'), nullable=False),
    sa.Column('tier', sa.Enum('note', 'shared', 'core', name='tier'), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'VERIFIED', 'REVIEW_DUE', 'STALE', 'ARCHIVED', name='status'), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('tags', sa.JSON(), nullable=False),
    sa.Column('author_id', sa.String(length=64), nullable=False),
    sa.Column('current_version_id', sa.Integer(), nullable=True),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('source_ref', sa.String(length=300), nullable=False),
    sa.Column('env_note', sa.String(length=200), nullable=False),
    sa.Column('status_reason', sa.Text(), nullable=False),
    sa.Column('reuse_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['current_version_id'], ['asset_version.id'], name='fk_knowledge_asset_current_version', use_alter=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('knowledge_asset', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_knowledge_asset_author_id'), ['author_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_knowledge_asset_status'), ['status'], unique=False)

    op.create_table('model',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('family', sa.String(length=64), nullable=False),
    sa.Column('arch_notes', sa.String(length=200), nullable=False),
    sa.Column('hf_ref', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('search_event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('query', sa.String(length=500), nullable=False),
    sa.Column('filters', sa.JSON(), nullable=False),
    sa.Column('mode', sa.String(length=16), nullable=False),
    sa.Column('result_ids', sa.JSON(), nullable=False),
    sa.Column('clicked_ids', sa.JSON(), nullable=False),
    sa.Column('session_id', sa.String(length=64), nullable=False),
    sa.Column('at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('search_event', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_search_event_session_id'), ['session_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_search_event_user_id'), ['user_id'], unique=False)

    op.create_table('asset_framework',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('framework_id', sa.Integer(), nullable=False),
    sa.Column('version_min', sa.String(length=40), nullable=False),
    sa.Column('version_max', sa.String(length=40), nullable=False),
    sa.Column('verified_on', sa.String(length=40), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['knowledge_asset.id'], ),
    sa.ForeignKeyConstraint(['framework_id'], ['framework.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('asset_framework', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_asset_framework_asset_id'), ['asset_id'], unique=False)

    op.create_table('asset_model',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('model_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['knowledge_asset.id'], ),
    sa.ForeignKeyConstraint(['model_id'], ['model.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('asset_model', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_asset_model_asset_id'), ['asset_id'], unique=False)

    op.create_table('asset_version',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('body_md', sa.Text(), nullable=False),
    sa.Column('change_note', sa.String(length=500), nullable=False),
    sa.Column('created_by', sa.String(length=64), nullable=False),
    sa.Column('created_from', sa.Enum('author', 'ai_draft', 'review', name='versionorigin'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['knowledge_asset.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('asset_version', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_asset_version_asset_id'), ['asset_id'], unique=False)

    # knowledge_asset.current_version_id -> asset_version.id 是环形外键，声明为 use_alter，
    # 因此不会出现在上面的 CREATE TABLE 里，必须在两张表都建好后单独补一条 ALTER。
    # SQLite 不支持 ALTER TABLE ADD CONSTRAINT（batch 模式会整表重建），本地用 sqlite 冒烟时跳过；
    # 生产目标库 PostgreSQL 正常执行。
    if op.get_context().dialect.name != 'sqlite':
        op.create_foreign_key(
            'fk_knowledge_asset_current_version', 'knowledge_asset', 'asset_version',
            ['current_version_id'], ['id'],
        )

    op.create_table('code_reference',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.Enum('repo_path', 'config_key', 'issue', 'pr', name='refkind'), nullable=False),
    sa.Column('repo', sa.String(length=200), nullable=False),
    sa.Column('path_or_key', sa.String(length=400), nullable=False),
    sa.Column('ref_id', sa.String(length=100), nullable=False),
    sa.Column('note', sa.String(length=300), nullable=False),
    sa.Column('watch', sa.Boolean(), nullable=False),
    sa.Column('last_seen_sha', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['knowledge_asset.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('code_reference', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_code_reference_asset_id'), ['asset_id'], unique=False)

    op.create_table('knowledge_gap',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question', sa.String(length=500), nullable=False),
    sa.Column('hit_count', sa.Integer(), nullable=False),
    sa.Column('first_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('reporters', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('claimed_by', sa.String(length=64), nullable=False),
    sa.Column('resolved_asset_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['resolved_asset_id'], ['knowledge_asset.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('status_transition',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('from_status', sa.Enum('DRAFT', 'VERIFIED', 'REVIEW_DUE', 'STALE', 'ARCHIVED', name='status'), nullable=True),
    sa.Column('to_status', sa.Enum('DRAFT', 'VERIFIED', 'REVIEW_DUE', 'STALE', 'ARCHIVED', name='status'), nullable=False),
    sa.Column('trigger', sa.Enum('auto_create', 'nonauthor_reuse', 'manual_validation', 'code_change', 'version_change', 'user_feedback', 'review_confirm', 'review_accept_draft', 'review_stale', 'review_replace', name='transition_trigger'), nullable=False),
    sa.Column('evidence_type', sa.String(length=40), nullable=False),
    sa.Column('evidence_id', sa.Integer(), nullable=True),
    sa.Column('actor', sa.String(length=64), nullable=False),
    sa.Column('note', sa.Text(), nullable=False),
    sa.Column('at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['knowledge_asset.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('status_transition', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_status_transition_asset_id'), ['asset_id'], unique=False)

    op.create_table('user_feedback',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=True),
    sa.Column('search_event_id', sa.Integer(), nullable=True),
    sa.Column('kind', sa.String(length=24), nullable=False),
    sa.Column('note', sa.String(length=500), nullable=False),
    sa.Column('at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['knowledge_asset.id'], ),
    sa.ForeignKeyConstraint(['search_event_id'], ['search_event.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reuse_event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('version_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('task_note', sa.String(length=500), nullable=False),
    sa.Column('outcome', sa.String(length=16), nullable=False),
    sa.Column('search_event_id', sa.Integer(), nullable=True),
    sa.Column('fw_version_at_use', sa.String(length=64), nullable=False),
    sa.Column('at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['knowledge_asset.id'], ),
    sa.ForeignKeyConstraint(['search_event_id'], ['search_event.id'], ),
    sa.ForeignKeyConstraint(['version_id'], ['asset_version.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('reuse_event', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reuse_event_asset_id'), ['asset_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_reuse_event_user_id'), ['user_id'], unique=False)

    op.create_table('review_task',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('trigger', sa.Enum('auto_create', 'nonauthor_reuse', 'manual_validation', 'code_change', 'version_change', 'user_feedback', 'review_confirm', 'review_accept_draft', 'review_stale', 'review_replace', name='transition_trigger'), nullable=False),
    sa.Column('trigger_detail', sa.Text(), nullable=False),
    sa.Column('diff_ref', sa.String(length=400), nullable=False),
    sa.Column('ai_impact_summary', sa.Text(), nullable=False),
    sa.Column('ai_draft_version_id', sa.Integer(), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('state', sa.String(length=16), nullable=False),
    sa.Column('handled_by', sa.String(length=64), nullable=False),
    sa.Column('action', sa.String(length=24), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('handled_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['ai_draft_version_id'], ['asset_version.id'], ),
    sa.ForeignKeyConstraint(['asset_id'], ['knowledge_asset.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('review_task', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_review_task_asset_id'), ['asset_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_review_task_state'), ['state'], unique=False)

    op.create_table('validation_record',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('version_id', sa.Integer(), nullable=True),
    sa.Column('validator_id', sa.String(length=64), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('result', sa.String(length=32), nullable=False),
    sa.Column('env_snapshot', sa.JSON(), nullable=False),
    sa.Column('note', sa.Text(), nullable=False),
    sa.Column('at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['knowledge_asset.id'], ),
    sa.ForeignKeyConstraint(['version_id'], ['asset_version.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('validation_record', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_validation_record_asset_id'), ['asset_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # 先摘掉环形外键，否则 knowledge_asset / asset_version 互相依赖无法 drop。
    if op.get_context().dialect.name != 'sqlite':
        op.drop_constraint('fk_knowledge_asset_current_version', 'knowledge_asset', type_='foreignkey')
    with op.batch_alter_table('validation_record', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_validation_record_asset_id'))

    op.drop_table('validation_record')
    with op.batch_alter_table('review_task', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_review_task_state'))
        batch_op.drop_index(batch_op.f('ix_review_task_asset_id'))

    op.drop_table('review_task')
    with op.batch_alter_table('reuse_event', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reuse_event_user_id'))
        batch_op.drop_index(batch_op.f('ix_reuse_event_asset_id'))

    op.drop_table('reuse_event')
    op.drop_table('user_feedback')
    with op.batch_alter_table('status_transition', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_status_transition_asset_id'))

    op.drop_table('status_transition')
    op.drop_table('knowledge_gap')
    with op.batch_alter_table('code_reference', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_code_reference_asset_id'))

    op.drop_table('code_reference')
    with op.batch_alter_table('asset_version', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_asset_version_asset_id'))

    op.drop_table('asset_version')
    with op.batch_alter_table('asset_model', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_asset_model_asset_id'))

    op.drop_table('asset_model')
    with op.batch_alter_table('asset_framework', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_asset_framework_asset_id'))

    op.drop_table('asset_framework')
    with op.batch_alter_table('search_event', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_search_event_user_id'))
        batch_op.drop_index(batch_op.f('ix_search_event_session_id'))

    op.drop_table('search_event')
    op.drop_table('model')
    with op.batch_alter_table('knowledge_asset', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_knowledge_asset_status'))
        batch_op.drop_index(batch_op.f('ix_knowledge_asset_author_id'))

    op.drop_table('knowledge_asset')
    op.drop_table('framework')
    # ### end Alembic commands ###
